### ISSUE TITLE
Acks to unencrypted messages broken after exchange closure

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#10515]
#### Problem
Consider the case of an unencrypted message coming in after the exchange it was targeting has been closed (e.g. it's a duplicate of the last message in a handshake, because the other side never got our ack).

We land in `ExchangeManager::OnMessageReceived` and don't match any existing exchanges.  We create a new exchange to handle the standalone ack.  We do this check:
```
        if (ec->IsEncryptionRequired() != packetHeader.GetFlags().Has(Header::FlagValues::kEncryptedMessage))
            ChipLogError(ExchangeManager, "OnMessageReceived failed, err = %s", ErrorStr(CHIP_ERROR_INVALID_MESSAGE_TYPE));
            ec->Close();
            return;
```
and the condition tests true, because the standalone ack exchange has no delegate, hence uses the `mDefaultExchangeDispatch` of the exchange manager, which is an `ApplicationExchangeDispatch`, which requires encryption.

So we never send the ack.

 #### Proposed Solution
Fix things so we send acks properly.

@pan-apple @kghost

**Comment by kghost** [comment]
Can we remove exchange dispatcher now ? As you can see, there is almost no difference between application dispatcher and session establishment dispatcher.

**Comment by kghost** [comment]
This should be fixed by #12794

**Comment by bzbarsky-apple** [comment]
This is not fixed. The behavior is still exactly the same: null-delegate exchanges default to `ApplicationExchangeDispatch::Instance()`, which requires encryption.
