### ISSUE TITLE
[Test-TC-BI-2.1]Optional Attribute of Binary Input Cluster seem to be missing

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#11142]
#### Problem
The optional attributes specified for the binary input cluster seem to be missing.

**Spec Reference**
![image](https://user-images.githubusercontent.com/12559578/139309418-b8004a30-a368-4cf2-9696-05b844bba042.png)

**YAML Test Script Error Logs**
![image](https://user-images.githubusercontent.com/12559578/139309506-a4fc662d-3219-4897-ad66-aba2427a54d1.png)

**Comment by andy31415** [comment]
Generation seems to say "OutOfService" to be missing, which is mandatory ... however then the text names it "out of service".

I think we should fix the mandatory item, however optional attributes should not block 1.0

**Comment by andy31415** [comment]
Checked `Test_TC_BI_2_1.yaml` and the out of service test seems enabled, so I assume it is working.

There is a comment saying that due to this bug, optional attribute checks are disabled. This seems consistent with the bug stating that only optional attributes are not working.

**Comment by manjunathambiger23** [comment]
@andy31415  this issue is regarding missing optional attributes of "Binary input cluster" which are still not implemented in YAML.

**Comment by bzbarsky-apple** [comment]
Fixed in #18209.
