### ISSUE TITLE
[BUG] JNI crash when we have active event/path subscriptions

### ISSUE THREAD

**Issue by jagadeesh-ayla** [project-chip/connectedhomeip#25044]
### Reproduction steps

1. Commission Device.
2. Subscribe to path using chipdevicecontroller.subscribeToPath API.
3. Observe the report callback is triggered for every changes on clusters.
4. after 2-3 minutes `java.lang.IllegalStateException: ../../src/app/ReadClient.cpp:889: CHIP Error 0x00000032: Timeout: 50` error is reported and within couple of seconds it crashes with below logs
```
Chip stack locking error at '../../src/transport/Session.h:187'. Code is unsafe/racy
chipDie chipDie chipDie
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24216 (FinalizerDaemon), pid 24201 (example.aura)
Cmdline: com.example.aura
pid: 24201, tid: 24216, name: FinalizerDaemon  >>> com.example.aura <<<
      #01 pc 00000000000fbc04  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #02 pc 000000000110f138  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #03 pc 000000000110f0c8  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #04 pc 0000000001120a60  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #05 pc 000000000112033c  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #06 pc 00000000011202c4  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #07 pc 000000000011ac18  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #08 pc 00000000010ad888  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #09 pc 00000000000f6f64  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #10 pc 00000000000f6f00  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #11 pc 00000000000f705c  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #12 pc 00000000000f5ba4  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk (Java_chip_devicecontroller_ReportCallbackJni_deleteCallback+132)
      #15 pc 0000000000401716  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/oat/arm64/base.vdex (chip.devicecontroller.ReportCallbackJni.finalize+22)
```

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

Latest

### Platform

android

### Anything else?

Chip stack locking error at '../../src/transport/Session.h:187'. Code is unsafe/racy
chipDie chipDie chipDie
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24216 (FinalizerDaemon), pid 24201 (example.aura)
Cmdline: com.example.aura
pid: 24201, tid: 24216, name: FinalizerDaemon  >>> com.example.aura <<<
      #01 pc 00000000000fbc04  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #02 pc 000000000110f138  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #03 pc 000000000110f0c8  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #04 pc 0000000001120a60  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #05 pc 000000000112033c  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #06 pc 00000000011202c4  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #07 pc 000000000011ac18  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #08 pc 00000000010ad888  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #09 pc 00000000000f6f64  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #10 pc 00000000000f6f00  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #11 pc 00000000000f705c  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk
      #12 pc 00000000000f5ba4  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/base.apk (Java_chip_devicecontroller_ReportCallbackJni_deleteCallback+132)
      #15 pc 0000000000401716  /data/app/~~Cm60AwtdCsX4Y5bQ_m_mHA==/com.example.aura-M1RcLFHrhODmCmnsFP62cA==/oat/arm64/base.vdex (chip.devicecontroller.ReportCallbackJni.finalize+22)

**Comment by yunhanw-google** [comment]
fixed.

**Comment by brueggenthies-adesso** [comment]
Hey,
we are currently using the Matter SDK Version 1.5 (freshly build on last friday), and are still experiencing this (or a similar) crash on Android.

> 2025-11-25 14:16:17.327 27811-27811 DEBUG                   pid-27811                            A  Cmdline: com.wago.homeapp.dev
2025-11-25 14:16:17.327 27811-27811 DEBUG                   pid-27811                            A  pid: 26210, tid: 26218, name: FinalizerDaemon  >>> com.wago.homeapp.dev <<<
2025-11-25 14:16:17.327 27811-27811 DEBUG                   pid-27811                            A        #07 pc 000000000039575c  /data/app/~~fGQxfJNcvpspSoBV-tmeUg==/com.wago.homeapp.dev-nwIk9yxdF3WcDWYu738tEw==/base.apk (offset 0xbc0000)
2025-11-25 14:16:17.327 27811-27811 DEBUG                   pid-27811                            A        #08 pc 0000000000395710  /data/app/~~fGQxfJNcvpspSoBV-tmeUg==/com.wago.homeapp.dev-nwIk9yxdF3WcDWYu738tEw==/base.apk (offset 0xbc0000)
2025-11-25 14:16:17.327 27811-27811 DEBUG                   pid-27811                            A        #09 pc 000000000038c8a0  /data/app/~~fGQxfJNcvpspSoBV-tmeUg==/com.wago.homeapp.dev-nwIk9yxdF3WcDWYu738tEw==/base.apk (offset 0xbc0000) (Java_chip_devicecontroller_ReportCallbackJni_deleteCallback+36)
2025-11-25 14:16:17.327 27811-27811 DEBUG                   pid-27811                            A        #15 pc 00000000025ab964  /data/app/~~fGQxfJNcvpspSoBV-tmeUg==/com.wago.homeapp.dev-nwIk9yxdF3WcDWYu738tEw==/oat/arm64/base.vdex (chip.devicecontroller.ReportCallbackJni.finalize+0)

This crash occurs after a certain time when we have subscriptions opened during this time.
Could this be related to the initial report?
