### ISSUE TITLE
Attribute persistence provider API change issues

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#27823]
@hicklin Please see https://github.com/project-chip/connectedhomeip/pull/27611#pullrequestreview-1520069631

@tcarmelveilleux @tobiasgraf 

If we're going to make an API change here, we should think pretty hard about what the API should look like instead of taking EmberAfAttributeMetadata....  The type+size may not be the right thing.

Plus the various other issues.  And the fact that this breaks API compat for SDK consumers.

**Comment by hicklin** [comment]
What we can do is overload the `ReadValue` function with the same signature as before and make that function call the new `ReadValue`. That should solve to issue of SDK consumers calling a function that currently does not exist.

**Comment by bzbarsky-apple** [comment]
> That should solve to issue of SDK consumers calling a function that currently does not exist.

No, you misunderstand.  The SDK consumers _implement_ this function.  This is the API you implement, as an SDK consumer, to handle attributes being written.  You can leave it as the "thing that uses the KVS", or you can implement your own persistence provider.  And in the latter case you will now no longer compile, because we broke backwards compat.

**Comment by hicklin** [comment]
Fixed [here](https://github.com/project-chip/connectedhomeip/pull/28302).

**Comment by bzbarsky-apple** [comment]
Unfortunately, not fixed @hicklin.  Specifically, https://github.com/project-chip/connectedhomeip/pull/27611#discussion_r1256564193 is not addressed yet.
