### ISSUE TITLE
[Darwin] Constraints arithmetic operations build error.

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#29505]
### Reproduction steps

Summary: 
[Test Suites - Darwin (no-ble-asan-clang)] was failing in PR [29339](https://github.com/project-chip/connectedhomeip/pull/29339) since according to the specification the minimum value for MaxMeasuredValue is `MinMeasuredValue + 1` and the YAML MinValue was modified as MaxMeasuredValue + 1, Darwin does not seem to support the arithmetic operations of the constraints.

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:Darwin_Constraints_Arthmetic_Operaton_Error

Reproduction steps:
Run TC-FLW-2.1 or TC-RH-2.1 with the patch in [Test Suites - Darwin (no-ble-asan-clang)](https://github.com/project-chip/connectedhomeip/actions/runs/6328638633/job/17187259315?pr=29339#logs)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

433e6769389c5e127e8d88418d1dae3150e39534

### Platform

darwin

### Anything else?

Spec screenshot:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/ec4fad5b-b66c-4ed3-8b48-d36590ee3cb3)
Execution logs:
[logs_2103922.zip](https://github.com/project-chip/connectedhomeip/files/12762692/logs_2103922.zip)
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/82920d54-4409-4bfb-b2d1-b46a3e98147c)

**Comment by bzbarsky-apple** [comment]
This is going to be fixed by moving to the python driver instead of codegen tests.

**Comment by woody-apple** [comment]
I believe this is now resolved?

**Comment by bzbarsky-apple** [comment]
This is not resolved....  The relevant tests have just beed disabled on darwin-framework-tool.

**Comment by woody-apple** [comment]
@manjunath-grl Are you able to check to see if this test is still disabled, and/or if it is passing now? Please re-open if still an issue.
