### ISSUE TITLE
[BUG] Build issue in Camera-App (RPi 5)

### ISSUE THREAD

**Issue by joyoungjun** [project-chip/connectedhomeip#38933]
### Reproduction steps

Command  used to build the camera-app(Sample App)
 ./scripts/examples/gn_build_example.sh examples/camera-app/linux/ examples/camera-app/linux/out/camera-app chip_inet_config_enable_ipv4=false

Logs
`2025-05-14 01:47:11,163 Loading extra packages for linux
2025-05-14 01:47:11,163 Skipping: darwin (i.e. /home/ubuntu/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/python311.json)
2025-05-14 01:47:11,163 Skipping: windows (i.e. /home/ubuntu/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/python311.json)

  WELCOME TO...

         █
         █
     ▄   █   ▄                                █     █
     ▀▀█████▀▀      ▄▀▀▀▄ ▄▀▀▀▄    ▄▀▀▀▀▄█  ▀▀█▀▀▀▀▀█▀▀   ▄▀▀▀▀▄    ▄▀▀
   ▀█▄       ▄█▀   █     █     █  █      █    █     █    █▄▄▄▄▄▄█  █
     ▀█▄   ▄█▀     █     █     █  █      █    █     █    █         █
  ▄██▀▀█   █▀▀██▄  █     █     █   ▀▄▄▄▄▀█    ▀▄▄   ▀▄▄   ▀▄▄▄▄▀   █
 ▀▀    █   █    ▀▀

  ACTIVATOR! This sets your shell environment variables.

Activating environment (setting environment variables):

  Setting environment variables for CIPD package manager...done
  Setting environment variables for Project actions........skipped
  Setting environment variables for Python environment.....done
  Setting environment variables for pw packages............skipped
  Setting environment variables for Host tools.............done

Checking the environment:

20250514 01:47:11 INF Environment passes all checks!

Environment looks good, you are ready to go!

+ env
SHELL=/bin/bash
PW_PROJECT_ROOT=/home/ubuntu/connectedhomeip
PW_ZAP_CIPD_INSTALL_DIR=/home/ubuntu/connectedhomeip/.environment/cipd/packages/zap
PWD=/home/ubuntu/connectedhomeip
LOGNAME=ubuntu
XDG_SESSION_TYPE=tty
CIPD_CACHE_DIR=/home/ubuntu/.cipd-cache-dir
PW_ROOT=/home/ubuntu/connectedhomeip/third_party/pigweed/repo
HOME=/home/ubuntu
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:
VIRTUAL_ENV=/home/ubuntu/connectedhomeip/.environment/pigweed-venv
LC_TERMINAL=iTerm2
SSH_CONNECTION=192.168.1.31 52636 192.168.1.32 22
_PW_ROSETTA=0
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=ubuntu
LC_TERMINAL_VERSION=3.5.13
SHLVL=2
PW_PACKAGE_ROOT=/home/ubuntu/connectedhomeip/.environment/packages
XDG_SESSION_ID=16
_PW_ENVIRONMENT_CONFIG_FILE=/home/ubuntu/connectedhomeip/scripts/setup/environment.json
XDG_RUNTIME_DIR=/run/user/1000
PW_BRANDING_BANNER=/home/ubuntu/connectedhomeip/scripts/setup/banner.txt
_PW_ACTUAL_ENVIRONMENT_ROOT=/home/ubuntu/connectedhomeip/.environment
SSH_CLIENT=192.168.1.31 52636 22
PW_ARM_CIPD_INSTALL_DIR=/home/ubuntu/connectedhomeip/.environment/cipd/packages/arm
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/ubuntu/connectedhomeip/third_party/pigweed/repo/out/host/host_tools:/home/ubuntu/connectedhomeip/.environment/pigweed-venv/bin:/home/ubuntu/connectedhomeip/.environment/cipd/packages/arm/bin:/home/ubuntu/connectedhomeip/.environment/cipd/packages/arm:/home/ubuntu/connectedhomeip/.environment/cipd/packages/zap:/home/ubuntu/connectedhomeip/.environment/cipd/packages/pigweed/bin:/home/ubuntu/connectedhomeip/.environment/cipd/packages/pigweed:/home/ubuntu/connectedhomeip/.environment/cipd:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SSH_TTY=/dev/pts/0
PW_PIGWEED_CIPD_INSTALL_DIR=/home/ubuntu/connectedhomeip/.environment/cipd/packages/pigweed
OLDPWD=/home/ubuntu/connectedhomeip
_=/usr/bin/env
+ gn gen --check --fail-on-unused-args --root=examples/camera-app/linux/ examples/camera-app/linux/out/camera-app --args=chip_inet_config_enable_ipv4=false
Done. Made 5784 targets from 532 files in 2759ms
+ ninja -C examples/camera-app/linux/out/camera-app
ninja: Entering directory `examples/camera-app/linux/out/camera-app'
[91/102] ACTION //third_party/connecte...build/toolchain/linux:linux_arm64_gcc)
-- The CXX compiler identification is GNU 13.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- The C compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at deps/usrsctp/CMakeLists.txt:33 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Looking for include file sys/queue.h
-- Looking for include file sys/queue.h - found
-- Looking for include files sys/socket.h, linux/if_addr.h
-- Looking for include files sys/socket.h, linux/if_addr.h - found
-- Looking for include files sys/socket.h, linux/rtnetlink.h
-- Looking for include files sys/socket.h, linux/rtnetlink.h - found
-- Looking for 4 include files sys/types.h, ..., netinet/ip_icmp.h
-- Looking for 4 include files sys/types.h, ..., netinet/ip_icmp.h - found
-- Looking for 3 include files sys/types.h, ..., net/route.h
-- Looking for 3 include files sys/types.h, ..., net/route.h - found
-- Looking for include file stdatomic.h
-- Looking for include file stdatomic.h - found
-- Looking for usrsctp.h
-- Looking for usrsctp.h - found
-- Performing Test have_sa_len
-- Performing Test have_sa_len - Failed
-- Performing Test have_sin_len
-- Performing Test have_sin_len - Failed
-- Performing Test have_sin6_len
-- Performing Test have_sin6_len - Failed
-- Performing Test have_sconn_len
-- Performing Test have_sconn_len - Failed
-- Performing Test has_wfloat_equal
-- Performing Test has_wfloat_equal - Success
-- Performing Test has_wshadow
-- Performing Test has_wshadow - Success
-- Performing Test has_wpointer_aritih
-- Performing Test has_wpointer_aritih - Success
-- Performing Test has_wunreachable_code
-- Performing Test has_wunreachable_code - Success
-- Performing Test has_winit_self
-- Performing Test has_winit_self - Success
-- Performing Test has_wno_unused_function
-- Performing Test has_wno_unused_function - Success
-- Performing Test has_wno_unused_parameter
-- Performing Test has_wno_unused_parameter - Success
-- Performing Test has_wno_unreachable_code
-- Performing Test has_wno_unreachable_code - Success
-- Performing Test has_wstrict_prototypes
-- Performing Test has_wstrict_prototypes - Success
-- Compiler flags (CMAKE_C_FLAGS):  -std=c99 -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wpointer-arith -Wunreachable-code -Winit-self -Wno-unused-function -Wno-unused-parameter -Wno-unreachable-code -Wstrict-prototypes
-- Performing Test has_wno_address_of_packed_member
-- Performing Test has_wno_address_of_packed_member - Success
-- Performing Test has_wno_deprecated_declarations
-- Performing Test has_wno_deprecated_declarations - Success
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - found
-- Looking for byteswap.h
-- Looking for byteswap.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for machine/types.h
-- Looking for machine/types.h - not found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for sys/int_types.h
-- Looking for sys/int_types.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for winsock2.h
-- Looking for winsock2.h - not found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for inet_aton
-- Looking for inet_aton - found
-- Looking for inet_pton
-- Looking for inet_pton - found
-- Looking for usleep
-- Looking for usleep - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found suitable version "3.0.13", minimum required is "1.1.0")
-- Could NOT find PCAP (missing: PCAP_LIBRARY)
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "3.0.13")
-- Using the multi-header code from /home/ubuntu/connectedhomeip/third_party/libdatachannel/repo/deps/json/include/
-- Configuring done (20.6s)
-- Generating done (0.5s)
-- Build files have been written to: /home/ubuntu/connectedhomeip/third_party/libdatachannel/repo/build
[  1%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/addr.c.o
[  1%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_asconf.c.o
[  1%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/agent.c.o
[  1%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_auth.c.o
[  3%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o
[  3%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_callout.c.o
[  3%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_cc_functions.c.o
[  3%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/crc32.c.o
[  5%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/const_time.c.o
[  5%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/conn.c.o
[  5%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/conn_poll.c.o
[  7%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/conn_thread.c.o
[  8%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_crc32.c.o
[  8%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/conn_mux.c.o
[  8%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_indata.c.o
[  8%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/base64.c.o
[ 10%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/hash.c.o
[ 10%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/hmac.c.o
[ 10%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/ice.c.o
[ 12%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/juice.c.o
[ 12%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/log.c.o
[ 12%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/random.c.o
[ 14%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/server.c.o
[ 14%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/stun.c.o
[ 14%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_input.c.o
[ 14%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/timestamp.c.o
[ 16%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/turn.c.o
[ 16%] Building C object deps/libjuice/CMakeFiles/juice.dir/src/udp.c.o
[ 16%] Linking C static library libjuice.a
[ 16%] Built target juice
[ 16%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/srtp/srtp.c.o
[ 17%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_output.c.o
[ 17%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/aes_gcm_ossl.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/auth.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/auth_test_cases.c.o
[ 23%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/null_auth.c.o
[ 23%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/hmac_ossl.c.o
[ 23%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/alloc.c.o
[ 25%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/crypto_kernel.c.o
[ 25%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/err.c.o
[ 25%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/key.c.o
[ 26%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/math/datatypes.c.o
[ 26%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/replay/rdb.c.o
[ 26%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/replay/rdbx.c.o
[ 28%] Linking C static library libsrtp2.a
[ 28%] Built target srtp2
[ 28%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_pcb.c.o
[ 28%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_peeloff.c.o
[ 30%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_sha1.c.o
[ 30%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_ss_functions.c.o
[ 30%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_sysctl.c.o
[ 32%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_timer.c.o
[ 32%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_userspace.c.o
[ 32%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_usrreq.c.o
[ 33%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctputil.c.o
[ 33%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet6/sctp6_usrreq.c.o
[ 33%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/user_environment.c.o
[ 35%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/user_mbuf.c.o
[ 35%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/user_recv_thread.c.o
[ 35%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/user_socket.c.o
[ 37%] Linking C static library libusrsctp.a
[ 37%] Built target usrsctp
[ 39%] Building CXX object CMakeFiles/datachannel.dir/src/candidate.cpp.o
[ 39%] Building CXX object CMakeFiles/datachannel.dir/src/channel.cpp.o
[ 39%] Building CXX object CMakeFiles/datachannel.dir/src/configuration.cpp.o
[ 41%] Building CXX object CMakeFiles/datachannel.dir/src/datachannel.cpp.o
[ 41%] Building CXX object CMakeFiles/datachannel.dir/src/description.cpp.o
[ 41%] Building CXX object CMakeFiles/datachannel.dir/src/iceudpmuxlistener.cpp.o
[ 42%] Building CXX object CMakeFiles/datachannel.dir/src/mediahandler.cpp.o
[ 42%] Building CXX object CMakeFiles/datachannel.dir/src/global.cpp.o
[ 42%] Building CXX object CMakeFiles/datachannel.dir/src/message.cpp.o
[ 44%] Building CXX object CMakeFiles/datachannel.dir/src/peerconnection.cpp.o
[ 44%] Building CXX object CMakeFiles/datachannel.dir/src/rtcpreceivingsession.cpp.o
[ 44%] Building CXX object CMakeFiles/datachannel.dir/src/track.cpp.o
[ 46%] Building CXX object CMakeFiles/datachannel.dir/src/websocket.cpp.o
[ 46%] Building CXX object CMakeFiles/datachannel.dir/src/websocketserver.cpp.o
[ 46%] Building CXX object CMakeFiles/datachannel.dir/src/rtppacketizationconfig.cpp.o
[ 48%] Building CXX object CMakeFiles/datachannel.dir/src/rtcpsrreporter.cpp.o
[ 48%] Building CXX object CMakeFiles/datachannel.dir/src/rtppacketizer.cpp.o
[ 48%] Building CXX object CMakeFiles/datachannel.dir/src/rtpdepacketizer.cpp.o
[ 50%] Building CXX object CMakeFiles/datachannel.dir/src/h264rtppacketizer.cpp.o
[ 50%] Building CXX object CMakeFiles/datachannel.dir/src/h264rtpdepacketizer.cpp.o
[ 50%] Building CXX object CMakeFiles/datachannel.dir/src/nalunit.cpp.o
[ 51%] Building CXX object CMakeFiles/datachannel.dir/src/h265rtppacketizer.cpp.o
[ 51%] Building CXX object CMakeFiles/datachannel.dir/src/h265rtpdepacketizer.cpp.o
[ 51%] Building CXX object CMakeFiles/datachannel.dir/src/h265nalunit.cpp.o
[ 53%] Building CXX object CMakeFiles/datachannel.dir/src/av1rtppacketizer.cpp.o
[ 53%] Building CXX object CMakeFiles/datachannel.dir/src/rtcpnackresponder.cpp.o
[ 53%] Building CXX object CMakeFiles/datachannel.dir/src/rtp.cpp.o
[ 55%] Building CXX object CMakeFiles/datachannel.dir/src/capi.cpp.o
[ 55%] Building CXX object CMakeFiles/datachannel.dir/src/plihandler.cpp.o
[ 55%] Building CXX object CMakeFiles/datachannel.dir/src/pacinghandler.cpp.o
[ 57%] Building CXX object CMakeFiles/datachannel.dir/src/rembhandler.cpp.o
[ 57%] Building CXX object CMakeFiles/datachannel.dir/src/impl/certificate.cpp.o
[ 57%] Building CXX object CMakeFiles/datachannel.dir/src/impl/channel.cpp.o
[ 58%] Building CXX object CMakeFiles/datachannel.dir/src/impl/datachannel.cpp.o
[ 58%] Building CXX object CMakeFiles/datachannel.dir/src/impl/dtlssrtptransport.cpp.o
[ 58%] Building CXX object CMakeFiles/datachannel.dir/src/impl/dtlstransport.cpp.o
[ 60%] Building CXX object CMakeFiles/datachannel.dir/src/impl/icetransport.cpp.o
[ 60%] Building CXX object CMakeFiles/datachannel.dir/src/impl/iceudpmuxlistener.cpp.o
[ 60%] Building CXX object CMakeFiles/datachannel.dir/src/impl/init.cpp.o
[ 62%] Building CXX object CMakeFiles/datachannel.dir/src/impl/peerconnection.cpp.o
[ 62%] Building CXX object CMakeFiles/datachannel.dir/src/impl/logcounter.cpp.o
[ 62%] Building CXX object CMakeFiles/datachannel.dir/src/impl/sctptransport.cpp.o
[ 64%] Building CXX object CMakeFiles/datachannel.dir/src/impl/threadpool.cpp.o
[ 64%] Building CXX object CMakeFiles/datachannel.dir/src/impl/tls.cpp.o
[ 64%] Building CXX object CMakeFiles/datachannel.dir/src/impl/track.cpp.o
[ 66%] Building CXX object CMakeFiles/datachannel.dir/src/impl/utils.cpp.o
[ 66%] Building CXX object CMakeFiles/datachannel.dir/src/impl/processor.cpp.o
[ 66%] Building CXX object CMakeFiles/datachannel.dir/src/impl/sha.cpp.o
[ 67%] Building CXX object CMakeFiles/datachannel.dir/src/impl/pollinterrupter.cpp.o
[ 67%] Building CXX object CMakeFiles/datachannel.dir/src/impl/pollservice.cpp.o
[ 67%] Building CXX object CMakeFiles/datachannel.dir/src/impl/http.cpp.o
[ 69%] Building CXX object CMakeFiles/datachannel.dir/src/impl/httpproxytransport.cpp.o
[ 69%] Building CXX object CMakeFiles/datachannel.dir/src/impl/tcpserver.cpp.o
[ 69%] Building CXX object CMakeFiles/datachannel.dir/src/impl/tcptransport.cpp.o
[ 71%] Building CXX object CMakeFiles/datachannel.dir/src/impl/tlstransport.cpp.o
[ 71%] Building CXX object CMakeFiles/datachannel.dir/src/impl/transport.cpp.o
[ 71%] Building CXX object CMakeFiles/datachannel.dir/src/impl/verifiedtlstransport.cpp.o
[ 73%] Building CXX object CMakeFiles/datachannel.dir/src/impl/websocket.cpp.o
[ 73%] Building CXX object CMakeFiles/datachannel.dir/src/impl/websocketserver.cpp.o
[ 73%] Building CXX object CMakeFiles/datachannel.dir/src/impl/wstransport.cpp.o
[ 75%] Building CXX object CMakeFiles/datachannel.dir/src/impl/wshandshake.cpp.o
[ 75%] Linking CXX static library libdatachannel.a
[ 75%] Built target datachannel
[ 75%] Building CXX object CMakeFiles/datachannel-tests.dir/test/main.cpp.o
[ 75%] Building CXX object CMakeFiles/datachannel-benchmark.dir/test/benchmark.cpp.o
[ 76%] Building CXX object CMakeFiles/datachannel-tests.dir/test/connectivity.cpp.o
[ 78%] Linking CXX executable benchmark
[ 78%] Built target datachannel-benchmark
[ 78%] Building CXX object examples/client/CMakeFiles/datachannel-client.dir/main.cpp.o
[ 78%] Building CXX object CMakeFiles/datachannel-tests.dir/test/negotiated.cpp.o
[ 78%] Building CXX object CMakeFiles/datachannel-tests.dir/test/reliability.cpp.o
[ 80%] Building CXX object CMakeFiles/datachannel-tests.dir/test/turn_connectivity.cpp.o
[ 80%] Building CXX object examples/client/CMakeFiles/datachannel-client.dir/parse_cl.cpp.o
[ 80%] Building CXX object CMakeFiles/datachannel-tests.dir/test/track.cpp.o
[ 82%] Linking CXX executable client
[ 82%] Built target datachannel-client
[ 82%] Building CXX object examples/client-benchmark/CMakeFiles/datachannel-client-benchmark.dir/main.cpp.o
[ 82%] Building CXX object CMakeFiles/datachannel-tests.dir/test/capi_connectivity.cpp.o
[ 83%] Building CXX object CMakeFiles/datachannel-tests.dir/test/capi_track.cpp.o
[ 83%] Building CXX object CMakeFiles/datachannel-tests.dir/test/websocket.cpp.o
[ 83%] Building CXX object CMakeFiles/datachannel-tests.dir/test/websocketserver.cpp.o
[ 85%] Building CXX object CMakeFiles/datachannel-tests.dir/test/capi_websocketserver.cpp.o
[ 85%] Building CXX object CMakeFiles/datachannel-tests.dir/test/benchmark.cpp.o
[ 85%] Building CXX object examples/client-benchmark/CMakeFiles/datachannel-client-benchmark.dir/parse_cl.cpp.o
[ 85%] Linking CXX executable tests
[ 85%] Built target datachannel-tests
[ 87%] Linking CXX executable client-benchmark
[ 89%] Building CXX object examples/media-receiver/CMakeFiles/datachannel-media-receiver.dir/main.cpp.o
[ 89%] Built target datachannel-client-benchmark
[ 89%] Building CXX object examples/media-sender/CMakeFiles/datachannel-media-sender.dir/main.cpp.o
[ 89%] Linking CXX executable media-receiver
[ 91%] Built target datachannel-media-receiver
[ 91%] Linking CXX executable media-sender
[ 91%] Building CXX object examples/media-sfu/CMakeFiles/datachannel-media-sfu.dir/main.cpp.o
[ 91%] Built target datachannel-media-sender
[ 91%] Building CXX object examples/streamer/CMakeFiles/streamer.dir/main.cpp.o
[ 91%] Linking CXX executable media-sfu
[ 91%] Built target datachannel-media-sfu
[ 91%] Building CXX object examples/copy-paste/CMakeFiles/datachannel-copy-paste-offerer.dir/offerer.cpp.o
[ 91%] Linking CXX executable offerer
[ 92%] Building CXX object examples/streamer/CMakeFiles/streamer.dir/dispatchqueue.cpp.o
[ 92%] Built target datachannel-copy-paste-offerer
[ 92%] Building CXX object examples/copy-paste/CMakeFiles/datachannel-copy-paste-answerer.dir/answerer.cpp.o
[ 92%] Building CXX object examples/streamer/CMakeFiles/streamer.dir/h264fileparser.cpp.o
[ 92%] Linking CXX executable answerer
[ 92%] Building CXX object examples/streamer/CMakeFiles/streamer.dir/helpers.cpp.o
[ 92%] Built target datachannel-copy-paste-answerer
[ 94%] Building CXX object examples/streamer/CMakeFiles/streamer.dir/opusfileparser.cpp.o
[ 94%] Building CXX object examples/streamer/CMakeFiles/streamer.dir/fileparser.cpp.o
[ 94%] Building CXX object examples/streamer/CMakeFiles/streamer.dir/stream.cpp.o
[ 96%] Building CXX object examples/streamer/CMakeFiles/streamer.dir/ArgParser.cpp.o
[ 96%] Building C object examples/copy-paste-capi/CMakeFiles/datachannel-copy-paste-capi-offerer.dir/offerer.c.o
[ 98%] Linking CXX executable offerer-capi
[ 98%] Built target datachannel-copy-paste-capi-offerer
[100%] Building C object examples/copy-paste-capi/CMakeFiles/datachannel-copy-paste-capi-answerer.dir/answerer.c.o
[100%] Linking CXX executable answerer-capi
[100%] Linking CXX executable streamer
[100%] Built target datachannel-copy-paste-capi-answerer
[100%] Built target streamer
Changed directory to: /home/ubuntu/connectedhomeip/examples/camera-app/linux/third_party/connectedhomeip/third_party/libdatachannel/scripts/../repo
Running: cmake -B build -DUSE_GNUTLS=0 -DUSE_NICE=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-Wno-shadow -DBUILD_SHARED_LIBS=OFF
Changed directory to: /home/ubuntu/connectedhomeip/examples/camera-app/linux/third_party/connectedhomeip/third_party/libdatachannel/scripts/../repo/build
Running: make -j2
libdatachannel build complete.
Artifacts are located in: /home/ubuntu/connectedhomeip/examples/camera-app/linux/third_party/connectedhomeip/third_party/libdatachannel/scripts/../repo/build
[99/102] c++ obj/third_party/connected...rc/chip-camera-app.camera-device.cpp.o
FAILED: [code=1] obj/third_party/connectedhomeip/examples/camera-app/linux/src/chip-camera-app.camera-device.cpp.o
aarch64-linux-gnu-g++ -MMD -MF obj/third_party/connectedhomeip/examples/camera-app/linux/src/chip-camera-app.camera-device.cpp.o.d -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Werror -Wextra -Wshadow -Wunreachable-code -Wvla -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wno-deprecated-declarations -Wno-missing-field-initializers -Wno-unknown-warning-option -Wno-unused-parameter -Wno-cast-function-type -Wno-psabi -Wno-maybe-uninitialized -fdiagnostics-color -fno-strict-aliasing -Wconversion -Wno-shadow -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu -fmacro-prefix-map=../../third_party/connectedhomeip/= -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -Wno-format-nonliteral -Wno-format-nonliteral -std=gnu++17 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -DCHIP_MINMDNS_USE_EPHEMERAL_UNICAST_PORT=1 -DCHIP_MINMDNS_HIGH_VERBOSITY=0 -DCHIP_MINMDNS_DEFAULT_POLICY=1 -I../../include -I../../include/clusters/chime -I../../include/clusters/webrtc_provider -I../../include/clusters/camera-avstream-mgmt -I../../include/clusters/camera-avsettingsuserlevel-mgmt -I../../include/media-controller -I../../include/network-stream-source -I../../include/transport -I../../third_party/connectedhomeip/examples/camera-app/camera-common/include -I../../third_party/connectedhomeip/examples/camera-app/camera-common/include/media-controller -I../../third_party/connectedhomeip/examples/camera-app/camera-common/include/transport -I../../third_party/connectedhomeip/third_party/libdatachannel/repo/include -Igen/third_party/connectedhomeip/examples/camera-app/camera-common -Igen/third_party/connectedhomeip/examples/camera-app/camera-common/zapgen -I../../third_party/connectedhomeip/src/include -I../../third_party/connectedhomeip/src -Igen/include -I../../third_party/connectedhomeip/examples/camera-app/linux/include -I../../third_party/connectedhomeip/config/standalone -I../../third_party/connectedhomeip/zzz_generated/app-common -I../../third_party/connectedhomeip/third_party/nlassert/repo/include -I../../third_party/connectedhomeip/third_party/nlio/repo/include -I../../third_party/connectedhomeip/third_party/nlfaultinjection/include -I../../third_party/connectedhomeip/third_party/inipp/repo/inipp -I../../third_party/connectedhomeip/src/tracing/perfetto/include -I../../third_party/connectedhomeip/third_party/perfetto/repo/sdk -I../../third_party/connectedhomeip/examples/platform/linux -I../../third_party/connectedhomeip/third_party/jsoncpp/repo/include -c ../../third_party/connectedhomeip/examples/camera-app/linux/src/camera-device.cpp -o obj/third_party/connectedhomeip/examples/camera-app/linux/src/chip-camera-app.camera-device.cpp.o
In file included from /usr/include/gstreamer-1.0/gst/gst.h:91,
                 from ../../include/camera-device.h:30,
                 from ../../third_party/connectedhomeip/examples/camera-app/linux/src/camera-device.cpp:19:
/usr/include/gstreamer-1.0/gst/gstutils.h: In function ‘void GST_WRITE_FLOAT_LE(guint8*, gfloat)’:
/usr/include/gstreamer-1.0/gst/gstutils.h:169:78: error: conversion from ‘guint32’ {aka ‘unsigned int’} to ‘guint8’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  169 |     (((guint8 *) (__data))[__idx] = (((guint##__size) (__num)) >> (__shift)) & 0xff)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:473:43: note: in expansion of macro ‘_GST_PUT’
  473 |                                           _GST_PUT (__put_data, 3, 32, 24, __put_val); \
      |                                           ^~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:789:3: note: in expansion of macro ‘GST_WRITE_UINT32_LE’
  789 |   GST_WRITE_UINT32_LE (data, u.i);
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h: In function ‘void GST_WRITE_FLOAT_BE(guint8*, gfloat)’:
/usr/include/gstreamer-1.0/gst/gstutils.h:169:78: error: conversion from ‘guint32’ {aka ‘unsigned int’} to ‘guint8’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  169 |     (((guint8 *) (__data))[__idx] = (((guint##__size) (__num)) >> (__shift)) & 0xff)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:461:43: note: in expansion of macro ‘_GST_PUT’
  461 |                                           _GST_PUT (__put_data, 0, 32, 24, __put_val); \
      |                                           ^~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:809:3: note: in expansion of macro ‘GST_WRITE_UINT32_BE’
  809 |   GST_WRITE_UINT32_BE (data, u.i);
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h: In function ‘void GST_WRITE_DOUBLE_LE(guint8*, gdouble)’:
/usr/include/gstreamer-1.0/gst/gstutils.h:169:78: error: conversion from ‘guint64’ {aka ‘long unsigned int’} to ‘guint8’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  169 |     (((guint8 *) (__data))[__idx] = (((guint##__size) (__num)) >> (__shift)) & 0xff)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:431:43: note: in expansion of macro ‘_GST_PUT’
  431 |                                           _GST_PUT (__put_data, 7, 64, 56, __put_val); \
      |                                           ^~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:829:3: note: in expansion of macro ‘GST_WRITE_UINT64_LE’
  829 |   GST_WRITE_UINT64_LE (data, u.i);
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h: In function ‘void GST_WRITE_DOUBLE_BE(guint8*, gdouble)’:
/usr/include/gstreamer-1.0/gst/gstutils.h:169:78: error: conversion from ‘guint64’ {aka ‘long unsigned int’} to ‘guint8’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  169 |     (((guint8 *) (__data))[__idx] = (((guint##__size) (__num)) >> (__shift)) & 0xff)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:411:43: note: in expansion of macro ‘_GST_PUT’
  411 |                                           _GST_PUT (__put_data, 0, 64, 56, __put_val); \
      |                                           ^~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:849:3: note: in expansion of macro ‘GST_WRITE_UINT64_BE’
  849 |   GST_WRITE_UINT64_BE (data, u.i);
      |   ^~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
[101/102] c++ obj/chip-camera-app.main.cpp.o
FAILED: [code=1] obj/chip-camera-app.main.cpp.o
aarch64-linux-gnu-g++ -MMD -MF obj/chip-camera-app.main.cpp.o.d -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Werror -Wextra -Wshadow -Wunreachable-code -Wvla -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wno-deprecated-declarations -Wno-missing-field-initializers -Wno-unknown-warning-option -Wno-unused-parameter -Wno-cast-function-type -Wno-psabi -Wno-maybe-uninitialized -fdiagnostics-color -fno-strict-aliasing -Wconversion -Wno-shadow -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu -fmacro-prefix-map=../../third_party/connectedhomeip/= -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -Wno-format-nonliteral -Wno-format-nonliteral -std=gnu++17 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -DCHIP_MINMDNS_USE_EPHEMERAL_UNICAST_PORT=1 -DCHIP_MINMDNS_HIGH_VERBOSITY=0 -DCHIP_MINMDNS_DEFAULT_POLICY=1 -I../../include -I../../include/clusters/chime -I../../include/clusters/webrtc_provider -I../../include/clusters/camera-avstream-mgmt -I../../include/clusters/camera-avsettingsuserlevel-mgmt -I../../include/media-controller -I../../include/network-stream-source -I../../include/transport -I../../third_party/connectedhomeip/examples/camera-app/camera-common/include -I../../third_party/connectedhomeip/examples/camera-app/camera-common/include/media-controller -I../../third_party/connectedhomeip/examples/camera-app/camera-common/include/transport -I../../third_party/connectedhomeip/third_party/libdatachannel/repo/include -Igen/third_party/connectedhomeip/examples/camera-app/camera-common -Igen/third_party/connectedhomeip/examples/camera-app/camera-common/zapgen -I../../third_party/connectedhomeip/src/include -I../../third_party/connectedhomeip/src -Igen/include -I../../third_party/connectedhomeip/examples/camera-app/linux/include -I../../third_party/connectedhomeip/config/standalone -I../../third_party/connectedhomeip/zzz_generated/app-common -I../../third_party/connectedhomeip/third_party/nlassert/repo/include -I../../third_party/connectedhomeip/third_party/nlio/repo/include -I../../third_party/connectedhomeip/third_party/nlfaultinjection/include -I../../third_party/connectedhomeip/third_party/inipp/repo/inipp -I../../third_party/connectedhomeip/src/tracing/perfetto/include -I../../third_party/connectedhomeip/third_party/perfetto/repo/sdk -I../../third_party/connectedhomeip/examples/platform/linux -I../../third_party/connectedhomeip/third_party/jsoncpp/repo/include -c ../../main.cpp -o obj/chip-camera-app.main.cpp.o
In file included from /usr/include/gstreamer-1.0/gst/gst.h:91,
                 from ../../include/camera-device.h:30,
                 from ../../main.cpp:19:
/usr/include/gstreamer-1.0/gst/gstutils.h: In function ‘void GST_WRITE_FLOAT_LE(guint8*, gfloat)’:
/usr/include/gstreamer-1.0/gst/gstutils.h:169:78: error: conversion from ‘guint32’ {aka ‘unsigned int’} to ‘guint8’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  169 |     (((guint8 *) (__data))[__idx] = (((guint##__size) (__num)) >> (__shift)) & 0xff)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:473:43: note: in expansion of macro ‘_GST_PUT’
  473 |                                           _GST_PUT (__put_data, 3, 32, 24, __put_val); \
      |                                           ^~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:789:3: note: in expansion of macro ‘GST_WRITE_UINT32_LE’
  789 |   GST_WRITE_UINT32_LE (data, u.i);
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h: In function ‘void GST_WRITE_FLOAT_BE(guint8*, gfloat)’:
/usr/include/gstreamer-1.0/gst/gstutils.h:169:78: error: conversion from ‘guint32’ {aka ‘unsigned int’} to ‘guint8’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  169 |     (((guint8 *) (__data))[__idx] = (((guint##__size) (__num)) >> (__shift)) & 0xff)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:461:43: note: in expansion of macro ‘_GST_PUT’
  461 |                                           _GST_PUT (__put_data, 0, 32, 24, __put_val); \
      |                                           ^~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:809:3: note: in expansion of macro ‘GST_WRITE_UINT32_BE’
  809 |   GST_WRITE_UINT32_BE (data, u.i);
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h: In function ‘void GST_WRITE_DOUBLE_LE(guint8*, gdouble)’:
/usr/include/gstreamer-1.0/gst/gstutils.h:169:78: error: conversion from ‘guint64’ {aka ‘long unsigned int’} to ‘guint8’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  169 |     (((guint8 *) (__data))[__idx] = (((guint##__size) (__num)) >> (__shift)) & 0xff)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:431:43: note: in expansion of macro ‘_GST_PUT’
  431 |                                           _GST_PUT (__put_data, 7, 64, 56, __put_val); \
      |                                           ^~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:829:3: note: in expansion of macro ‘GST_WRITE_UINT64_LE’
  829 |   GST_WRITE_UINT64_LE (data, u.i);
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h: In function ‘void GST_WRITE_DOUBLE_BE(guint8*, gdouble)’:
/usr/include/gstreamer-1.0/gst/gstutils.h:169:78: error: conversion from ‘guint64’ {aka ‘long unsigned int’} to ‘guint8’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  169 |     (((guint8 *) (__data))[__idx] = (((guint##__size) (__num)) >> (__shift)) & 0xff)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:411:43: note: in expansion of macro ‘_GST_PUT’
  411 |                                           _GST_PUT (__put_data, 0, 64, 56, __put_val); \
      |                                           ^~~~~~~~
/usr/include/gstreamer-1.0/gst/gstutils.h:849:3: note: in expansion of macro ‘GST_WRITE_UINT64_BE’
  849 |   GST_WRITE_UINT64_BE (data, u.i);
      |   ^~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
ubuntu@ubuntu:~/connectedhomeip$`

### Bug prevalence

whenever I do this

### GitHub hash of the SDK that was being used

b8b0116b2c71e1db9e3db23d5596083da1badb51

### Platform

raspi

### Platform Version(s)

Raspberrypi 5

**Comment by kiel-apple** [comment]
fingers crossed this is solved by #38770

**Comment by joyoungjun** [comment]
@kiel-apple Thanks for letting me know, but unfortunately it doesn't solve the problem. I'm still getting the same error.

**Comment by kiel-apple** [comment]
because the errors are in `gstreamer`, I think the issue is with the the distribution-provided `gstreamer` package rather than with code on the Matter side, which will make it more challenging to resolve.

**Comment by joyoungjun** [comment]
Oh, then it will take some time to resolve. Thanks for letting me know.

**Comment by yufengwangca** [comment]
https://github.com/project-chip/connectedhomeip/tree/master/examples/camera-app/linux

Lets know if there is still any issue, this build is under CI.
